Add xfce CI test cases

diff --git a/.github/workflows/test_nixos_full.yml b/.github/workflows/test_nixos_full.yml
--- a/.github/workflows/test_nixos_full.yml
+++ b/.github/workflows/test_nixos_full.yml
@@ -91,3 +91,38 @@ jobs:
             -e 's/environment.systemPackages = with pkgs; \[ test-asterinas \];/environment.systemPackages = with pkgs; \[ hello-asterinas \];/' \
             -e 's/^[[:space:]]*virtualisation\.podman\.enable = true;/  # virtualisation.podman.enable = true;/' \
             distro/etc_nixos/configuration.nix
+
+  xfce-test:
+    runs-on: ubuntu-4-cores-150GB-ssd
+    container:
+      image: asterinas/asterinas:0.17.0-20251213
+      options: -v /dev:/dev --privileged
+    timeout-minutes: 20
+    steps:
+      - uses: actions/checkout@v4
+      - name: Modify configuration.nix to include test-asterinas and xserver and xfce
+        run: |
+          sed -i \
+            -e 's/environment.systemPackages = with pkgs; \[ hello-asterinas \];/environment.systemPackages = with pkgs; \[ test-asterinas \];/' \
+            -e 's/^[[:space:]]*# services\.xserver\.enable = true;/  services.xserver.enable = true;/' \
+            -e 's/^[[:space:]]*# services\.xserver\.desktopManager\.xfce\.enable = true;/  services.xserver.desktopManager.xfce.enable = true;/' \
+            distro/etc_nixos/configuration.nix
+
+      - name: Run xfce session tests
+        run: |
+          make nixos NIXOS_DISK_SIZE_IN_MB=8192 NIXOS_TEST_COMMAND='test-xfce'
+          make run_nixos || true
+
+      - name: Check results
+        run: |
+          tail --lines 100 qemu.log | grep -q "^Test xfce succeeds" || (echo "Test xfce failed" && exit 1)
+          echo "Test xfce succeeds!"
+
+      - name: Restore configuration.nix
+        if: always()
+        run: |
+          sed -i \
+            -e 's/environment.systemPackages = with pkgs; \[ test-asterinas \];/environment.systemPackages = with pkgs; \[ hello-asterinas \];/' \
+            -e 's/^[[:space:]]*services\.xserver\.enable = true;/  # services.xserver.enable = true;/' \
+            -e 's/^[[:space:]]*services\.xserver\.desktopManager\.xfce\.enable = true;/  # services.xserver.desktopManager.xfce.enable = true;/' \
+            distro/etc_nixos/configuration.nix
