Support nix-shell by logging in as root

diff --git a/.github/workflows/test_nixos_full.yml b/.github/workflows/test_nixos_full.yml
--- a/.github/workflows/test_nixos_full.yml
+++ b/.github/workflows/test_nixos_full.yml
@@ -1,7 +1,7 @@
 # A comprehensive test for NixOS.
 #
 # This test suite is designed to run on GitHub's larger runners,
-# leveraging their extended storage capacity. 
+# leveraging their extended storage capacity.
 # Here, we can thoroughly test a wider range of NixOS commands and various applications.
 # As GitHub charges more for these premium runners,
 # these tests will only run when changes are detected in AsterNixOS-specific content.
@@ -33,7 +33,12 @@ jobs:
       - uses: actions/checkout@v4
       - name: Use nix-env to install and run the hello package
         run: |
-          make run NIXOS=1 NIXOS_DISK_SIZE_IN_MB=4096 NIXOS_STAGE_2_INIT="nix-env -iA nixos.hello && hello && sync" || true
+          make run NIXOS=1 NIXOS_DISK_SIZE_IN_MB=4096 NIXOS_STAGE_2_INIT='/bin/sh -l -c "nix-env -iA nixos.hello && hello && sync"' || true
           tail --lines 10 qemu.log | grep -q "^Hello, world!" || (echo "Test nix-env failed" && exit 1)
           echo "Test nix-env succeeds!"
+      - name: Use nix-shell to install and run the hello package
+        run: |
+          make run NIXOS=1 NIXOS_DISK_SIZE_IN_MB=4096 NIXOS_STAGE_2_INIT='/bin/sh -l -c "nix-shell -p hello --command hello && sync"' || true
+          tail --lines 10 qemu.log | grep -q "^Hello, world!" || (echo "Test nix-shell failed" && exit 1)
+          echo "Test nix-shell succeeds!"
 
